drop table if exists entries;
create table entries(
  id integer primary key autoincrement,
  msp text,
  name_first text, 
  name_mi text, 
  name_last text, 
  dob text,
  sex text,
  ssn text, 
  marital_status text, 
  phone text, 
  phone_other text, 
  address text, 
  city text, 
  state text,
  zip text, 
  county text, 
  mailing_address text, 
  mailing_city text,
  mailing_state text, 
  mailing_zip text, 
  mailing_county text, 
  homeless text, 
  applying text,
  voterreg text, 
  language text, 
  interpreter text, 
  race_asian text, 
  race_black text, 
  race_aina text,
  race_pinh text, 
  race_white text, 
  hispanic text, 
  reservation text
);
